RegisterCommand('fixinvis', function(source, args)
    Citizen.Wait(5)
    local playerPed = PlayerPedId()
    SetEntityLocallyVisible(playerPed)
    NetworkSetEntityInvisibleToNetwork(playerPed, false)
    SetPlayerVisibleLocally(source, true)
    SetEntityVisible(playerPed, true, 0)
    SetLocalPlayerVisibleLocally(true)
end, false)